# FROM node:20-bullseye

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# # Generate Prisma client
# RUN npx prisma generate

# # Build the application using build script
# RUN chmod +x build.sh && ./build.sh

# EXPOSE 3000

# ENV NODE_ENV=production
# CMD ["npm", "start"]
FROM node:20-bullseye

WORKDIR /app

COPY package*.json ./
RUN npm install

CMD ["sh", "-c", "npx prisma generate && WATCHPACK_POLLING=true next dev -H 0.0.0.0 -p 3000"]

